<?php

use Drupal\Core\Template\Attribute;
use Drupal\present\Element\RevealJSPresentation;

/**
 * Implements hook_theme().
 */
function present_theme() {
  return [
    'revealjs_presentation' => [
      'render element' => 'presentation',
    ],
    'revealjs_slide' => [
      'render element' => 'slide',
    ],
    'present_vimeo_player' => [
      'render element' => 'vimeo',
    ]
  ];
}

function template_preprocess_revealjs_presentation(&$variables) {
  $presentation = $variables['presentation'];
  $variables['attributes'] = new Attribute($presentation['#attributes']);
  $variables['slides'] = $presentation['#slides'];
}

function template_preprocess_revealjs_slide(&$variables) {
  $slide = $variables['slide'];
  $variables['attributes'] = new Attribute($slide['#attributes']);
  $variables['content'] = $slide['#content'];
}

function template_preprocess_present_vimeo_player(&$variables) {
  $vimeo = $variables['vimeo'];
  $variables['attributes'] = new Attribute($vimeo['#attributes']);
}

/**
 * Implements hook_entity_type_alter().
 */
function present_entity_type_alter(array &$entity_types) {
  // Check if the user entity type exists.
  if (isset($entity_types['user'])) {
    $config = \Drupal::config('present.settings');
    $form_mode = $config->get('registration_form_mode');
    if ($form_mode != 'default') {
      $entity_types['user']->setFormClass($form_mode, 'Drupal\present\Form\UserPresentationRegisterForm');
    }
  }
}

/**
 * Implements hook_library_info_build()
 */
function present_library_info_build() {
  $libraries = [];
  // Add a library whose information changes depending on certain conditions.
  $defaults = [
    'header' => true,
    'dependencies' => [
      'present/library',
    ],
  ];
  foreach (array_keys(RevealJSPresentation::revealThemes()) as $theme) {
    $libraries['reveal-theme-' . $theme] = $defaults + [
      'css' => [
        'base' => [
          '/libraries/reveal.js/dist/theme/' . $theme . '.css' => ['minified' => TRUE]
        ],
      ],
    ];
  }
  return $libraries;
}

/**
 * Implements hook_token_info()
 */
function present_token_info() {
  // Core tokens for nodes.
  $vimeo_embed_options['url'] = [
    'name' => t("URL"),
    'description' => t("URL used to embed the video"),
  ];

  return [
    'types' => [
      'vimeo_embed_options' => [
        'name' => t('Vimeo Emebd Options'),
        'description' => t('Embed options used for initializing the vimeo player.'),
        'needs-data' => 'vimeo_embed_options',
      ]
    ],
    'tokens' => ['vimeo_embed_options' => $vimeo_embed_options],
  ];
}

/**
 * Implements hook_tokens()
 */
function present_tokens($type, $tokens, array $data, array $options) {
  $replacements = [];

  if ($type == 'vimeo_embed_options') {
    if (!empty($data['vimeo_embed_options'])) {
      foreach ($tokens as $name => $original) {
        switch ($name) {
          case 'url':
            $replacements[$original] = $data['vimeo_embed_options']['url'];
            break;
        }
      }
    }
  }

  return $replacements;
}
