<?php

use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function present_theme() {
  return [
    'revealjs_presentation' => [
      'render element' => 'presentation',
    ],
    'revealjs_slide' => [
      'render element' => 'slide',
    ],
    'present_vimeo_player' => [
      'render element' => 'vimeo',
    ]
  ];
}

function template_preprocess_revealjs_presentation(&$variables) {
  $presentation = $variables['presentation'];
  $variables['attributes'] = new Attribute($presentation['#attributes']);
  $variables['slides'] = $presentation['#slides'];
}

function template_preprocess_revealjs_slide(&$variables) {
  $slide = $variables['slide'];
  $variables['content'] = $slide['#content'];
}

function template_preprocess_present_vimeo_player(&$variables) {
  $vimeo = $variables['vimeo'];
  $variables['attributes'] = new Attribute($vimeo['#attributes']);
}

/**
 * Implements hook_entity_type_alter().
 */
function present_entity_type_alter(array &$entity_types) {
  // Check if the user entity type exists.
  if (isset($entity_types['user'])) {
    $entity_types['user']->setFormClass('presentation', 'Drupal\present\Form\UserPresentationRegisterForm');
  }
}
