# Schema for the configuration files of the present module.

present.settings:
  type: config_object
  label: 'Present settings'
  mapping:
    revealjs_theme:
      type: string
      label: 'Reveal.js Theme'
    user_code_cookied_validity:
      type: string
      label: 'Valid for Days'
    registration_form_mode:
      type: string
      label: 'Registration Form Mode'

present.presentation.*:
  type: config_entity
  label: 'Presentation'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Status'
    path:
      type: string
      label: 'Path'
    revealjs_theme:
      type: string
      label: 'Theme'
    slides:
      type: sequence
      label: 'Slides'
      sequence:
        type: mapping
        label: 'Slide'
        mapping:
          content:
            type: string
            label: 'Content'
          type:
            type: string
            label: 'Type of Content'
          auto_animate:
            type: boolean
            label: 'Auto Animate'
