# Schema for the configuration files of the present module.

present.settings:
  type: config_object
  label: 'Present settings'
  mapping:
    revealjs_theme:
      type: string
      label: 'Reveal.js Theme'

present.presentation.*:
  type: config_entity
  label: 'Presentation'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    status:
      type: boolean
      label: 'Status'
    revealjs_theme:
      type: string
      label: 'Theme'
    revealjs_plugins:
      type: sequence
      label: 'RevealJS Plugins'
      sequence:
        type: string
        label: 'RevealJS Plugin'
    revealjs_plugin_settings:
      type: sequence
      label: 'RevealJS Plugin Settings'
      sequence:
        type: config_object
        label: 'Plugin Settings'
    revealjs_config_options:
      type: string
      label: 'Config Options'
    events_to_track:
      type: sequence
      label: 'Events to Track'
      sequence:
        type: string
        label: 'Event'
    slides:
      type: sequence
      label: 'Slides'
      sequence:
        type: mapping
        label: 'Slide'
        mapping:
          content:
            type: string
            label: 'Content'
          type:
            type: string
            label: 'Type of Content'
          auto_animate:
            type: boolean
            label: 'Auto Animate'
          auto_animate_id:
            type: string
            label: 'Auto Animate ID'
          auto_animate_restart:
            type: boolean
            label: 'Auto Animate Restart'
          override_revealjs_config_options:
            type: sequence
            label: 'Override Config Options of Slide on Events'
            sequence:
              type: string
              label: 'Override Config Options of Slide on Event'
          autoslide:
            type: number
            label: 'Auto-Slide Duration'
          transition:
            type: mapping
            label: 'Transition'
            mapping:
              in:
                type: string
                label: 'In'
              out:
                type: string
                label: 'Out'
              speed:
                type: number
                label: 'Speed'
          background:
            type: mapping
            label: 'Background'
            mapping:
              color:
                type: string
                label: 'Color'
              gradient:
                type: string
                label: 'Gradient'
              image:
                type: string
                label: 'Image'
              size:
                type: string
                label: 'Size'
              position:
                type: string
                label: 'Position'
              repeat:
                type: string
                label: 'Repeat'
              opacity:
                type: number
                label: 'Opacity'
              interactive:
                type: boolean
                label: 'Interactive'
              video:
                type: mapping
                label: 'Video'
                mapping:
                  source:
                    type: string
                    label: 'Video Source'
                  loop:
                    type: boolean
                    label: 'Video Loop'
                  video_:
                    type: number
                    label: 'Video Speed'
              iframe:
                type: string
                label: 'iframe'
