# Schema for the configuration files of the present module.

present.settings:
  type: config_object
  label: 'Present settings'
  mapping:
    revealjs_theme:
      type: string
      label: 'Reveal.js Theme'
